### ISSUE TITLE
Cannot connect to Reolink battery powered camera

### ISSUE THREAD

**Issue by sanariaz154** [Benehiko/ReolinkCameraAPI#15]
I am trying to configure this API for Reaolink battery-powered camera. I have enabled port forwarding for the camera but still getting `requests.exceptions.ConnectionError: HTTPConnectionPool(host=ip, port=port): Max retries exceeded with url: /cgi-bin/api.cgi?cmd=Login&token=null`  error.

I there any way I can connect to the camera using UID of reolink instead of IP address?

**Comment by vlebourl** [comment]
I believe battery powered cameras cannot be supported as they don't have web browser remote access as stated in this support link https://support.reolink.com/hc/en-us/articles/360003981973-How-to-Remotely-Access-Reolink-Cameras-via-a-Web-Browser

**Comment by themoosman** [comment]
@sanariaz154 The Reolink battery-powered cameras don't use the same API as the PoE cameras.  AFAIK they use something proprietary.

**Comment by Lanwalker** [comment]
Reolink support ( support@reolink.com ) sent me a ' cgi-jsonv1.1.pdf ' describing JSON programming but it has all the commands for the other type cameras other than just for the battery powered Argus Pro and Argus PT versions. I am now trying to make sure that these commands will work on all their platforms or if not, I want a description to the commands for the battery systems since I have both of the cameras now and want to build my own personal version of the user interface to handle camera processes that are not built into the Argus Pro or the Argus PT ( like presets or a scan function for the PT version that I could not believe was not already in those cameras )... I just found the ' CGI_command.pdf ' and have not had a chance to look thru it yet )
If anybody has any code created for these, please let me know. I haven't been building software for a good while ( Disabled, hit by a drunk late to a softball game in a Ford F150 4x4 ( 45mph ) while coming home from work on my motorcycle ( 25 mph ) from the left side as he went high on a ' Y '... I somehow jerked my left leg up or he would have took it off as he went over my motorcycle ) and trying to get back into the Microsoft Visual Studio 2019 . I used to build software for test and control systems using assembly, pascal, C and C++ while working for United Technologies before 2001. ( and a lot has changed since then<G> )
Rfgamble@yahoo.com, Rfgamble@hotmail.com, Robert.gamble0@gmail.com
Here are the files to look over if interested
[cgi-jsonv1.1.pdf](https://github.com/Benehiko/ReolinkCameraAPI/files/5470417/cgi-jsonv1.1.pdf)
[CGI_command.pdf](https://github.com/Benehiko/ReolinkCameraAPI/files/5470418/CGI_command.pdf)

**Comment by Lanwalker** [comment]
(Reolink) Support

Nov 1, 2020, 17:45 GMT+8
Dear Robert Gamble,

Thank you for your reply!

According to the forum you sent, I need to explain that all of our battery-powered cameras can only be operated and connected through the Reolink APP or Reolink client. We did not design usable API commands.

Regarding the CGI files we sent, this is only suitable for specific models. Please refer to Which Reolink Products Support CGI_RTSP_ONVIF

Thanks for your patience.

Have a wonderful weekend! 😊

Best Regards
Reolink Support Team

**Comment by themoosman** [comment]
@Lanwalker This repo will only work against Reolink `RLC` cameras.  Do you have a question or issue about this repo?

**Comment by themoosman** [comment]
@Benehiko I think it's safe to close this issue.

**Comment by Lanwalker** [comment]
I was told they are working to get those issues fixed soon. Hopefully another version of the API will be released or they may update the current one inside the cameras ( and hope fully update how it transfers video and sound at the same time ... RTMP is out of date )

**Comment by surfzoid** [comment]
@Lanwalker i'm an linux user and have reolink argus 2 cam, as yu i search for an long time an solution, i can provide an wireshark packet of the conection but don't have enought time to reverse engeniering of them, have yu got time?

**Comment by Lanwalker** [comment]
I just purchased 3 Reolink E1 3MP HD Plug-in Indoor WiFi Cameras ( November 18, 2020 ), a Reolink Argus PT w/ Solar Panel ( October 25, 2020 ) and a Reolink Argus Pro w/ Solar Panel ( October 19, 2020.) and working on getting my software all configured to do some programming on the devices.

I used to build automated test and control systems for United Technologies Automotive and then Lear Corporation from 1983 until 2001 and was programming in assembly, Pascal and C / C++ and HP Rocky Mountain Basic and some Microsoft Basic ( mainly from other systems coming into our assembly plant ) along with all the different programmable controller software languages of Allen Bradley, GE and Siemans before 2001 but have not done any real machine / equipment programming since ( I've been doing web servers and web pages since then with Microsoft Expressions ). I was designing and building most of the test equipment from IC logic and relay logic before we implemented the controllers, computers and data acquisition systems... often using them combined for each specialty they brought to the systems.

I am physically disabled due to getting t-boned  by a Ford F150 4x4 ( 45 mph ) from the left side of my motorcycle ( 25 mph ) while coming home from work in April of 1985... I somehow jerked my left leg up just before he slammed my bike and the truck went over the bike and I destroyed his entire front end with my body, drove the radiator into the fan and drove his driver side fender into his tire before I bounced off and crawled up a hill on the other side of the ' y ' he was wide on as he was late for a softball game and driving drunk ( his cousin told me about that and showed me were he lived and what was left of the truck )... I seen him back off my motorcycle and as he got out I told him ' call the emergency squad, I think you killed me '.

These little devices sparked by interest in getting back into programming with all the features they have and I've been pulling down all types of software ( especially Microsoft Visual Studio and pieces ) and collecting routines to start back up... I used to have the earliest preview versions of all the Microsoft products while I was working coming from CPM/86 to DOS and into the Windows world and had the first Windows 95 system on our United Technologies network using it as a fax to email bridge and used Windows NT to emulate our Novell Servers during the Compaq server RAID controller crash during the year 2000 nightmare until we could get them back into operation and inserted back into the Novell 4 system ( The first time Novell and Compaq ever did that manipulation... I was their test bed<G> )... I was ' given ' the networks, servers and communication systems, including the AT&T Definity phone switch and Audix, the Cisco router and Ethernet switches ( Cabletron stomped them in my plant during a network test but corporate forced me to use Cisco ( I still think our head managers had stock in that company <G> ). Cisco used shorter delays in accessing the wire during collisions and I had the oscilloscope(s) proof from my $60,000 HP Logic Analyzer back then ) 

I've only had these about a month now... I needed something to watch over my home while I was at my doctors in Ohio ( I live in Florida on Space Coast now but do not trust new ' quacks' to practice on me anymore since new ' quacks ' in Ohio about killed me when I had to deal with the county health department when I was out of a job... nobody wants to hire damaged goods, no matter what your experience level is, especially after 911 )... I got stuck in Ohio last August until this October ( 14 months of freezing and muddy hell<G> ) due to vehicle problems ( hit a big pot hole in South Carolina and barely made it to Ohio ) and then that stupid Chinese Wuhan virus and now trying to get all this crap operational again. My old RV will not turn over yet, my old lime green Ford Festiva I use for fishing and the darn garden tractor and I just replaced all their batteries... do not let your vehicles sit that long without starting them !

I can barely walk anymore and my girl friend had to stay in Ohio to get some things done and I don't expect her to make it down here until after the first of the year now... that is why I got the cameras in the first place but I am not happy with the basic user interfaces for the Android phone or the Windows system these things have even though they have real decent features that just need some integration that the canned software does not provide.That is how I found this conversation on Github<G>

This gives me something to do<G>... I admin for the United States Minutemen groups and pages ( we had almost 4000 groups and pages on trashbook before they removed us ( me, all of our admins and most of the members in the entire country ) on August 19, 2020 at about 4:30 PM EST... took me about 7 months to create all them in 2011-2012 and Zuckerburg killed us and all the information we had collected in a matter of minutes and I have it all documented in a massive set of spread sheets with each state and all their counties and many other pieces of information like radio frequencies and some of the source information and links I used to put it all together ), now running on a $250 Windows 10 web server running on a laptop that started as a 4GB Windows 7 machine<G>
http://iii.thruhere.net/Social-Media-Sites/united_states_minutemen.html

I an now on SSD ( Social Security Disability ) and barely make a third ( maybe less ) of what I used to... but my house and vehicles are paid for and everything else except the new Trane AC unit I had to replace when I got back down here in October ( this place hit over a 100 the day I arrived.. first time I ever seen a thermostat read 00 and it kept on climbing ! ) <G>

Keep working at your projects, these are the times you'll have some of your most fun and the greatest memories as you make things work. ( Doesn't it feel like a game sometimes ? )
These links may help... Reolink IP wireless surveillance camera

Reolink IP wireless surveillance camera
    


or look over some of the other links I put on there.. I keep it raw and hardly any graphic for speed ( it's my internet notepad<G> )... United States Minutemen - American Patriots Coalition

 
 
 
   
United States Minutemen - American Patriots Coalition
    
 on MeWe.com...
Reolink cameras - Home Security cameras - https://mewe.com/join/reolinkcameras-homesecuritycameras

Minutemen Information Technologies - https://mewe.com/join/minutemeninformationtechnologies

Robert Gamble
Rfgamble@yahoo.com
Rfgamble@hotmail.com
Robert.gamble0@gmail.com ( Google lost my Rfgamble ID when it went from beta on Gmail and I never could get their ' support ' to fix it... one of my reasons I really dislike that company )
RobertFGamble@Att.net





On Sunday, November 22, 2020, 2:59:21 PM EST, surfzoid <notifications@github.com> wrote: 







@Lanwalker i'm an linux user and have reolink argus 2 cam, as yu i search for an long time an solution, i can provide an wireshark packet of the conection but don't have enought time to reverse engeniering of them, have yu got time?
