### ISSUE TITLE
Activate/deactivate sending emails in alert settings

### ISSUE THREAD

**Issue by bastelbert** [Benehiko/ReolinkCameraAPI#6]
Hi Benehiko,

first of all thank you for working on this huge topic, I really miss an official API from Reolink to my cams! 
This one is a feature request:
I would like to relate the sending of alert mails with my presence at home and the time of day.
So e.g. when my "smart home" detects that I left home it shall send a command to my Reolink cams to activate the sending of mails in case of alerts.
Sending of mails all day long is sometimes very annoying when we are around in the garden because we receive a lot of mails every few minutes.
I am using a Reolink Argus 2 and two RLC-422W so if you need a beta testers for new code feel free to contact me (unfortunalety I am no coder myself...).

Greetz
André

**Comment by Benehiko** [comment]
That would be out of the scope for this project since this "library" is actually only for communicating with the camera in your own app. If you can get someone to code you the actual app for making an association with you being home and the camera sending an alert, then they can use this library inside that app to speak to the camera. Right now this library only supports the basic functionality of the camera. I'd have to see if this camera has a way of alerting without an email. The email sending code will then have to be implemented separately from the camera's email sending software in your own software / app.
