### ISSUE TITLE
question - snapshot framerates

### ISSUE THREAD

**Issue by duffjay** [Benehiko/ReolinkCameraAPI#7]
Thanks for making your project public.     I want to set up a system where I am taking snapshots and sending the images into some computer vision models.    I started with Amcrest cameras and it was taking 1-2 seconds to get a frame from the camera - far too slow.    What has been your experience with the Reolink camera and your API?   Have you measured a frame-rate of grabbing images?   (I tried two methods - HTTP and OpenCV VideoCapture).    Thanks for responding to my question

**Comment by Benehiko** [comment]
Hi @duffjay, 
I did run into issues pulling snapshots from the Reolink over WiFi as the camera would "drop" off the network and from what I could tell, restart itself. The whole conversation over email is attached as a pdf here:
[Print - [Reolink] Pending request: RLC-411WS Camera connection drops.pdf](https://github.com/Benehiko/ReolinkCameraAPI/files/4233423/Print.-.Reolink.Pending.request.RLC-411WS.Camera.connection.drops.pdf)

Over LAN it was way more stable (such as 10-15fps per second if I can recall correctly). Just remember that opening a couple of camera streams (such as 4 cameras) on high bitrate will cause a lot of network traffic and computational power on the host machine - such as using OpenCV videocapture. It also causes the frames to build up a buffer which creates a ton of backlog. I found it best to use the snapshot rather since you don't build a buffer as it's only 1 frame you are pulling from the camera.

**Comment by duffjay** [comment]
As a followup, I am using Amcrest cameras.    I had a lot of performance problems that were unexplainable.  Very slow frame rates - using http or OpenCV.   And, it would generate all connection errors after approximately 200 shapshot requests.     I was giving up.

I upgraded the firmware on the camera.     (There was only a 6 month difference in the firmware dates so I wasn't expecting much.)   Wow, that fixed everything.     After upgrading the firmware, the Amcrest cameras performed as expected
